config/routes.rb
Rails.application.routes.draw do
  resources :deals
  resources :reminders
  resources :people
  resources :accounts
  resource :session
  resources :passwords, param: :token
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "users#home"

  namespace :typeaheads do
    resources :reminder_subjects, only: :index
    resources :accounts, only: :index
    resources :users, only: :index
  end
end

app/models/person.rb
class Person < ApplicationRecord
  include Remindable

  include SAL::BasicSearch
  basic_search :full_name, :first_name, :last_name

  belongs_to :account, inverse_of: :people
  belongs_to :phone_number, optional: true
  belongs_to :lead_source, class_name: "AccountLeadSource", optional: true
  belongs_to :address, optional: true
  belongs_to :owner, class_name: "User"
  
  # include created_by and last_updated_by associations and related callbacks
  include UserTracked

  normalizes :email_address, with: ->(e) { e.strip.downcase }
  validates :email_address, presence: true
  validates :email_address, format: { with: URI::MailTo::EMAIL_REGEXP }, if: -> (user) { user.email_address.present? }
  
  validates :first_name, presence: true
  validates :last_name, presence: true

  validates_associated :phone_number, :address

  def full_name
    "#{first_name} #{last_name}"
  end

  alias_method :name, :full_name

end

app/models/sal/configs/people.rb
class SAL::Configs::People < SAL::Config

  SEARCHABLES = [
    { search_method: :search_full_name, label: "Name" },
    { search_method: :search_email, label: "Email Address" }
  ]

  FILTERABLES = [
    {
      label: "Account",
      field: :account_id,
      klass: Account,
      typeahead: true,
      path: :typeaheads_accounts_path,
      options: {
        value_method: :id,
        text_method: :name,
        allow_multiple: true
      }
    },
    {
      label: "Lead Source",
      field: :lead_source_id,
      klass: AccountLeadSource,
      options: {
        collection: Proc.new { AccountLeadSource.order(:name) },
        value_method: :id,
        text_method: :name,
        allow_multiple: true
      }
    },
    {
      label: "Assigned To",
      field: :owner_id,
      klass: User,
      typeahead: true,
      path: :typeaheads_users_path,
      options: {
        value_method: :id,
        text_method: :full_name,
        allow_multiple: true
      }
    },
    {
      label: "Created At",
      field: :created_at
    }
  ]

  def klass
    Person
  end

  def countable
    "people"
  end

  def include_for_advanced_search
    [{ address: [:state_region, :country] }, :phone_number]
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  #include SAL::Analyzable

  include SAL::AdvancedSearchable

  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html do
          flash[:success] = "Person was successfully created."
          redirect_to @person
        end

        format.json { render :show, status: :created, location: @person}
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        
        format.html do 
          flash[:success] = "Person was successfully updated."
          redirect_to @person
        end

        format.json { render :show, status: :ok, location: @person}
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy!

    respond_to do |format|
      format.html { redirect_to people_path, status: :see_other, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :email_address, :account_id, :job_title, :owner_id, :lead_source_id)
    end

    def sal_config_klass
      SAL::Configs::People
    end
end

app/views/people/_advanced_search_results.html.erb
<div class="overflow-x-auto sm:rounded-lg mt-10">
  <table class="text-sm text-left text-gray-500">
    <thead class="text-xs text-gray-800 dark:text-white uppercase bg-gray-50 dark:bg-gray-700 whitespace-nowrap">
      <th scope="col" class="px-6 py-3">Name</th>
      <th scope="col" class="px-6 py-3">Assigned To</th>
      <th scope="col" class="px-6 py-3">Email Address</th>
      <th scope="col" class="px-6 py-3">Job Title</th>
      <th scope="col" class="px-6 py-3">Address</th>
      <th scope="col" class="px-6 py-3">Phone Number</th>
      <th scope="col" class="px-6 py-3">Lead Source</th>
      <th scope="col" class="px-6 py-3">Last Activity At</th>
      <th scope="col" class="px-6 py-3">Created By</th>
      <th scope="col" class="px-6 py-3">Last Updated By</th>      
    </thead>
    <tbody>
      <% @builder.results.each do |person| %>
        <tr class="bg-white hover:bg-gray-50 dark:bg-gray-500 dark:hover:bg-gray-400 text-gray-800 dark:text-white border-b border-gray-300 dark:border-gray-600">
          <th scope="row" class="px-6 py-4 font-medium whitespace-nowrap">
            <%= link_to person.full_name, person_path(person), data: { turbo: false } %>
          </th>
          <td class="px-6 py-4">
            <%= link_to_user(person.owner, data: { turbo: false }) %>
          </td>          
          <td class="px-6 py-4">
            <%= mail_to person.email_address %>
          </td>
          <td class="px-6 py-4">
            <%= person.job_title %>
          </td>
          <td class="px-6 py-4">
            <%= address_display(person.address) %>
          </td>
          <td class="px-6 py-4">
            <%= phone_display(person.phone_number) %>
          </td>
          <td class="px-6 py-4">
            <%= person.lead_source&.name %>
          </td>          
          <td class="px-6 py-4">
            <%= person.last_activity_at %>
          </td>
          <td class="px-6 py-4">
            <%= link_to_user(person.created_by, data: { turbo: false }) %>
          </td>          
          <td class="px-6 py-4">
            <%= link_to_user(person.last_updated_by, data: { turbo: false }) %>
          </td>                    
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/people/_details.html.erb
<div class='bg-white dark:bg-gray-800 text-gray-800 dark:text-white border border-gray-300 dark:border-gray-900 shadow rounded-md p-4'>
  <h2 class="font-bebas-neue text-4xl">Details</h2>
  <div class="py-4 border-b border-gray-300">
    <div>
      <span class="font-bold">Account: </span>
      <span><%= link_to @person.account.name, account_path(@person.account) %></span>
    </div>
    <div class="md:grid md:grid-cols-2 md:gap-4 mt-4">
      <div>
        <span class="font-bold">First Name: </span>
        <span><%= @person.first_name %></span>
      </div>
      <div>
        <span class="font-bold">Last Name: </span>
        <span><%= @person.last_name %></span>
      </div>
      <div>
        <span class="font-bold">Email Address: </span>
        <span><%= mail_to @person.email_address %></span>
      </div>
      <div>
        <span class="font-bold">Job Title: </span>
        <span><%= @person.job_title %></span>
      </div>    
      <div>
        <span class="font-bold">Phone Number: </span>
        <span><%= phone_display(@person.phone_number) %></span>
      </div>
      <div>
        <span class="font-bold">Lead Source: </span>
        <span><%= @person.lead_source&.name %></span>
      </div>
      <div>
        <span class="font-bold">Last Activity At: </span>
        <span><%= @person.last_activity_at %></span>
      </div>
    </div>
  </div>
  <div class="pt-4">
    <h6 class="text-xl">System Information</h6>
    <div class="md:grid md:grid-cols-2 md:gap-4 mt-4">
      <div>
        <span class="font-bold">Created By: </span>
        <span><%= link_to_user(@person.created_by) %></span>
      </div>
      <div>
        <span class="font-bold">Created At: </span>
        <span><%= @person.created_at %></span>
      </div>    
      <div>
        <span class="font-bold">Last Updated By: </span>
        <span><%= link_to_user(@person.last_updated_by) %></span>
      </div>
      <div>
        <span class="font-bold">Last Updated At: </span>
        <span><%= @person.updated_at %></span>
      </div>
    </div>
  </div>
</div>

app/views/people/_form.html.erb
<%= form_with(model: person, class: "contents") do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul class="list-disc ml-6">
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="relative z-0 w-full mb-5 md:mb-10 group">
    <%= form.text_field :first_name, required: true, class: "block py-2.5 px-0 w-full text-lg text-gray-800 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" %>
    <%= form.label :first_name, class: "peer-focus:font-medium absolute text-lg text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>    
  </div>

  <div class="relative z-0 w-full mb-5 md:mb-10 group">
    <%= form.text_field :last_name, required: true, class: "block py-2.5 px-0 w-full text-lg text-gray-800 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" %>
    <%= form.label :last_name, class: "peer-focus:font-medium absolute text-lg text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>    
  </div>

  <div class="relative z-0 w-full mb-5 md:mb-10 group">
    <%= form.email_field :email_address, required: true, class: "block py-2.5 px-0 w-full text-lg text-gray-800 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" %>
    <%= form.label :email_address, class: "peer-focus:font-medium absolute text-lg text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>    
  </div>

  <div class="relative z-0 w-full mb-5 md:mb-10 group">
    <%= content_tag :div, data: { controller: "typeahead-select", typeahead_select_url_value: typeaheads_accounts_path(value_method: :id, text_method: :name), typeahead_select_dimension_value: "person_account_id" } do %>
      <%= form.select :account_id, options_from_collection_for_select([@person.account].compact, :id, :name, @person.account&.id), { required: true }, data: { typeahead_select_target: "select" }, class: "block py-2.5 px-0 w-full text-lg text-gray-800 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" %>
    <% end %>
    <%= form.label :account_id, "Account", class: "peer-focus:font-medium absolute text-lg text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>    
  </div>   

  <div class="relative z-0 w-full mb-5 md:mb-10 group">
    <%= form.text_field :job_title, class: "block py-2.5 px-0 w-full text-lg text-gray-800 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" %>
    <%= form.label :job_title, class: "peer-focus:font-medium absolute text-lg text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>    
  </div>

<div class="relative z-0 w-full mb-5 md:mb-10 group">
    <%= form.select :owner_id, options_for_all_users(selected: selected_resource_owner(@person)), { required: true }, class: "block py-2.5 px-0 w-full text-lg text-gray-800 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" %>
    <%= form.label :owner_id, "Assigned To", class: "peer-focus:font-medium absolute text-lg text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>    
  </div>    

  <div class="relative z-0 w-full mb-5 md:mb-10 group">  
    <%= form.select :lead_source_id, options_from_collection_for_select(AccountLeadSource.all, :id, :name, @person.lead_source&.id), { include_blank: true }, class: "block py-2.5 px-0 w-full text-lg text-gray-800 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" %>
    <%= form.label :lead_source_id, class: "peer-focus:font-medium absolute text-lg text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %> 
  </div>     

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/people/_person.html.erb
<div id="<%= dom_id person %>" class="w-full sm:w-auto my-5 space-y-5">
  <div id="header-outer">
    <%= render partial: "resources/header", locals: { resource: @person } %>
  </div>
  <div class="md:flex md:flex-row">
    <div class="md:flex md:flex-col md:w-2/3 md:pr-3">
      <%= render partial: "details" %>
    </div>
    <div class="md:flex md:flex-col md:w-1/3 md:pl-3 mt-4 md:mt-0">
      <%= render partial: "resources/reminders", locals: { resource: @person } %>
    </div>
  </div>
</div>

app/views/people/edit.html.erb
<% content_for :title, @person.name %>

<div class="w-11/12 md:w-5/6 mx-auto w-full py-8 px-3 md:px-0">
  <div>
    <%= link_to "Show this person", @person, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
    <%= link_to "See all people", people_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  </div>
  <div class="mt-12 bg-white dark:bg-gray-800 text-gray-800 dark:text-white border border-gray-300 dark:border-gray-900 shadow rounded-md p-6">      
    <h1 class="font-bold text-4xl">Edit person</h1>
    <div class="mt-12">
      <%= render "form", person: @person %>
    </div>
  </div>
</div>

app/views/people/index.html.erb
<% content_for :title, "Contacts" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Contacts</h1>
    <%= link_to "New contact", new_contact_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="contacts" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @contacts.any? %>
      <% @contacts.each do |contact| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render contact %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", contact, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_contact_path(contact), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <div class="sm:inline-block">
              <%= button_to "Destroy", contact, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No contacts found.</p>
    <% end %>
  </div>
</div>

app/views/people/new.html.erb
<% content_for :title, @person.name %>

<div class="w-11/12 md:w-5/6 mx-auto w-full py-8 px-3 md:px-0">
  <div>
    <%= link_to "See all people", people_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  </div>
  <div class="mt-12 bg-white dark:bg-gray-800 text-gray-800 dark:text-white border border-gray-300 dark:border-gray-900 shadow rounded-md p-6">
    <h1 class="font-bold text-4xl">Create new person</h1>
    <div class="mt-12">
      <%= render "form", person: @person %>
    </div>
  </div>
</div>

app/views/people/show.html.erb
<% content_for :title, @person.full_name %>

<div class="w-11/12 md:w-5/6 mx-auto w-full py-8 px-3 md:px-0">
  <div class="mt-4">
    <%= link_to "Edit this person", edit_person_path(@person), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
    <%= link_to "See all people", people_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>

    <% if current_user_is_admin? %>
      <div class="sm:inline-block mt-2 sm:mt-0 sm:ml-2">
        <%= button_to "Destroy this person", @person, method: :delete, class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
      </div>
    <% end %>

    <%= link_to "Create New Reminder 🔔", new_reminder_path_for_resource(@person), class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-sky-500 hover:bg-sky-700 text-white inline-block font-medium" %>
  </div>

  <div class="mt-4">
    <%= render @person %>  
  </div>
</div>