config/routes.rb
Rails.application.routes.draw do
  resources :deals
  resources :reminders
  resources :people
  resources :accounts
  resource :session
  resources :passwords, param: :token
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "users#home"

  namespace :typeaheads do
    resources :reminder_subjects, only: :index
    resources :accounts, only: :index
    resources :users, only: :index
  end
end

app/views/shared/_navbar.html.erb
<nav id="nav" class="bg-cornflower-blue-900">
  <div class="w-5/6 mx-auto flex flex-wrap items-center justify-between mx-auto py-4">
    <%= link_to root_path, class: "flex items-center space-x-3 rtl:space-x-reverse text-lg md:text-2xl text-white font-bebas-neue" do %>
      <%= image_tag "no_salesforce.jpg", class: "h-12" %>&nbsp;No Salesforce!
    <% end %>    
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-white hover:text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-cornflower-blue-800 md:bg-cornflower-blue-900 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0">
        <% if authenticated? %>
          <li>
            <%= link_to "Accounts", accounts_path, class: "block py-2 px-3 text-md md:text-xl text-white hover:text-gray-400 rounded-sm md:bg-transparent md:p-0" %>
          </li>
          <li>
            <%= link_to "Deals", deals_path, class: "block py-2 px-3 text-md md:text-xl text-white hover:text-gray-400 rounded-sm md:bg-transparent md:p-0" %>
          </li>          
          <li>
            <%= link_to "People", people_path, class: "block py-2 px-3 text-md md:text-xl text-white hover:text-gray-400 rounded-sm md:bg-transparent md:p-0" %>
          </li>
          <li>
            <%= link_to "Reminders", reminders_path, class: "block py-2 px-3 text-md md:text-xl text-white hover:text-gray-400 rounded-sm md:bg-transparent md:p-0" %>
          </li>
        <% end %>
        <li>
          <%= navbar_signin_signout %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_spinner.html.erb
<div class='my-10 py-2'>
  <div class="text-center">
    <svg aria-hidden="true" class="inline w-24 h-24 mr-2 text-gray-200 animate-spin fill-blue-600" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"/>
        <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"/>
    </svg>
    <div class='my-4'>
      <span class="text-xl text-gray-800 dark:text-white"><%= spinner_text %></span>
    </div>
  </div>
</div>