config/routes.rb
Rails.application.routes.draw do
  resources :deals
  resources :reminders
  resources :people
  resources :accounts
  resource :session
  resources :passwords, param: :token
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "users#home"

  namespace :typeaheads do
    resources :reminder_subjects, only: :index
    resources :accounts, only: :index
    resources :users, only: :index
  end
end

app/views/resources/_activity_feed.html.erb
<div class='bg-white dark:bg-gray-800 text-gray-800 dark:text-white border border-gray-300 dark:border-gray-900 shadow rounded-md p-4'>
  <div>
    <h3 class="text-2xl">Activity Feed</h3>
    <div class="mt-2">
      <%= link_to "Create New Reminder", new_reminder_path %>
    </div>
  </div>

  <% if resource_has_past_due_reminders?(resource) %>
    <div class="py-4 border-b border-b-4 border-gray-300">
      <h5 class="text-xl text-red">Past Due:</h5>
      <div>
        <%= render_activity_feed_partial(past_due_reminders_collection(resource)) %>
      </div>
    </div>
  <% end %>

  <% if resource_has_upcoming_reminders?(resource) %>
    <div class="py-4 border-b border-b-4 border-gray-300">
      <h5 class="text-xl">Upcoming:</h5>
      <div>
        <%= render_activity_feed_partial(upcoming_reminders_collection(resource)) %>
      </div>
    </div>
  <% end %>

  <% if resource_has_completed_reminders?(resource) %>
    <div class="py-4">
      <h5 class="text-xl">Completed:</h5>
      <div>
        <%= render_activity_feed_partial(completed_reminders_collection(resource)) %>
      </div>
    </div>
  <% end %>
</div>

app/views/resources/_header.html.erb
<div class='bg-white dark:bg-gray-800 text-gray-800 dark:text-white border border-gray-300 dark:border-gray-900 shadow rounded-md p-4'>
  <h1 class="font-bebas-neue text-6xl"><%= resource.name %></h1>
  <div class="mt-2">
    <span class="text-2xl">(<%= resource_type_display(resource) %>) <%= resource_type_emoji(resource) %></span>
  </div>
  <div class="mt-2">
    <span class="text-2xl">Assigned To: <%= link_to_user resource.owner %></span>
  </div>
</div>

app/views/resources/_people.html.erb
<div class='bg-white dark:bg-gray-800 text-gray-800 dark:text-white border border-gray-300 dark:border-gray-900 shadow rounded-md p-4'>
  <h5 class="font-bebas-neue text-4xl">People</h5>
  <table class="text-sm text-left text-gray-500 mt-4">
    <thead class="text-xs text-gray-800 dark:text-white uppercase bg-gray-50 dark:bg-gray-700 whitespace-nowrap">
      <th scope="col" class="px-6 py-3">Name</th>
      <th scope="col" class="px-6 py-3">Email Address</th>
      <th scope="col" class="px-6 py-3">Job Title</th>
      <th scope="col" class="px-6 py-3">Owner</th>
    </thead>
    <tbody>
      <% resource.people.each do |person| %>
        <tr class="bg-white hover:bg-gray-50 dark:bg-gray-500 dark:hover:bg-gray-400 text-gray-800 dark:text-white border-b border-gray-300 dark:border-gray-600">
          <td class="px-6 py-4"><%= link_to person.full_name, person_path(person), data: { turbo: false } %></td>
          <td class="px-6 py-4"><%= person.email_address %></td>
          <td class="px-6 py-4"><%= person.job_title %></td>
          <td class="px-6 py-4"><%= link_to_user person.owner %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/resources/_reminders.html.erb
<div class='bg-white dark:bg-gray-800 text-gray-800 dark:text-white border border-gray-300 dark:border-gray-900 shadow rounded-md p-4'>
  <div>
    <h3 class="font-bebas-neue text-4xl">Reminders</h3>
  </div>

  <% if !resource_has_reminders?(resource) %>

    <div class="py-4">
      <span class="text-xl"><%= no_reminders_message(resource) %></span>
    </div>

  <% else %>

    <% if resource_has_past_due_reminders?(resource) %>
      <div class="py-4 border-b border-b-4 border-gray-300">
        <h5 class="text-xl text-red">Past Due ⚠️:</h5>
        <div>
          <%= render_reminders_partial(past_due_reminders_collection(resource)) %>
        </div>
        <div class="mt-2">
          <%= link_to_see_all_reminders(resource, :past_due) %>
        </div>        
      </div>
    <% end %>

    <% if resource_has_upcoming_reminders?(resource) %>
      <div class="py-4 border-b border-b-4 border-gray-300">
        <h5 class="text-xl">Upcoming ⏰:</h5>
        <div>
          <%= render_reminders_partial(upcoming_reminders_collection(resource).take(5)) %>
        </div>
        <div class="mt-2">
          <%= link_to_see_all_reminders(resource, :upcoming) %>
        </div>        
      </div>
    <% end %>

    <% if resource_has_complete_reminders?(resource) %>
      <div class="py-4">
        <h5 class="text-xl">Completed ✅:</h5>
        <div>
          <%= render_reminders_partial(completed_reminders_collection(resource).take(5)) %>
        </div>
      </div>
        <div class="mt-2">
          <%= link_to_see_all_reminders(resource, :complete) %>
        </div>      
    <% end %>

  <% end %>
</div>