config/routes.rb
Rails.application.routes.draw do
  resources :deals
  resources :reminders
  resources :people
  resources :accounts
  resource :session
  resources :passwords, param: :token
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "users#home"

  namespace :typeaheads do
    resources :reminder_subjects, only: :index
    resources :accounts, only: :index
    resources :users, only: :index
  end
end

app/models/account.rb
class Account < ApplicationRecord
  include SAL::BasicSearch
  basic_search :name

  include Remindable

  belongs_to :owner, class_name: "User"
  belongs_to :parent, class_name: "Account", optional: true
  belongs_to :phone_number, optional: true
  belongs_to :billing_address, class_name: "Address", optional: true
  belongs_to :shipping_address, class_name: "Address", optional: true

  # include created_by and last_updated_by associations and related callbacks
  include UserTracked

  belongs_to :industry, optional: true, inverse_of: :accounts
  belongs_to :account_source, class_name: "AccountLeadSource", optional: true, inverse_of: :accounts

  has_many :people, inverse_of: :account

  has_many :deals, inverse_of: :account

  validates :name, presence: true

  validates_associated :phone_number, :billing_address, :shipping_address
end

app/models/sal/configs/accounts.rb
class SAL::Configs::Accounts < SAL::Config

  SEARCHABLES = [
    { label: "Name", search_method: :search_name }
  ]

  FILTERABLES = [
    {
      label: "Industry",
      field: :industry_id,
      klass: Industry,
      options: {
        collection: Proc.new { Industry.order(:code) },
        value_method: :id,
        text_method: :name,
        allow_multiple: true
      }
    },
    {
      label: "Account Source",
      field: :account_source_id,
      klass: AccountLeadSource,
      options: {
        collection: Proc.new { AccountLeadSource.order(:name) },
        value_method: :id,
        text_method: :name,
        allow_multiple: true
      }
    },
    {
      label: "Assigned To",
      field: :owner_id,
      klass: User,
      options: {
        collection: Proc.new { User.all },
        value_method: :id,
        text_method: :full_name,
        allow_multiple: true
      }
    },
    {
      label: "Created At",
      field: :created_at
    }
  ]  

  def klass
    Account
  end

  def include_for_advanced_search
    [
      :owner,
      { billing_address: [:state_region, :country] },
      { shipping_address: [:state_region, :country] },
      :phone_number,
      :account_source,
      :created_by,
      :last_updated_by
    ]
  end
  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  include SAL::AdvancedSearchable

  before_action :set_account, only: %i[ show edit update destroy ]

  # index defined by SAL::AdvancedSearchable

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy!

    respond_to do |format|
      format.html { redirect_to accounts_path, status: :see_other, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:name, :owner_id, :description, :annual_revenue, :number_of_employees, :industry_id, :website, :incorporation_date, :account_source_id)
    end

    def sal_config_klass
      SAL::Configs::Accounts
    end

end

app/controllers/typeaheads/accounts_controller.rb
class Typeaheads::AccountsController < ApplicationController
  include Typeaheadable

  private

    def klass
      Account
    end

    def search_method
      :search_name
    end

end

app/helpers/accounts_helper.rb
module AccountsHelper

  def address_display(address)
    return if address.nil?

    [
      address.street,
      address.city,
      address.state_region&.abbreviation,
      address.country&.name,
      address.postal_code
    ].compact.join(", ")
  end

  def website_display(url)
    return if url.nil?

    # force to external url
    link_to url, "//#{url}", target: "_blank"
  end

  def incorporation_date_display(incorporation_date)
    incorporation_date&.to_formatted_s(:rfc822)
  end

  def account_has_people?(account)
    account.people.any?
  end

  def account_has_deals?(account)
    account.deals.any?
  end

  def deals_for_account
    @account.deals.order(close_date: :desc)
  end

end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>" class="w-full sm:w-auto my-5 space-y-5">
	<div id="header-outer">
		<%= render partial: "resources/header", locals: { resource: @account } %>
	</div>
	<div class="md:flex md:flex-row">
		<div class="md:flex md:flex-col md:w-2/3 md:pr-3">
			<%= render partial: "details" %>

      <% if account_has_deals?(account) %>
      	<div class="mt-4">
      		<%= render partial: "deals" %>
      	</div>
      <% end %>

      <% if account_has_people?(account) %>
        <div class="mt-4">
          <%= render partial: "resources/people", locals: { resource: @account } %>
        </div>
      <% end %>
		</div>
		<div class="md:flex md:flex-col md:w-1/3 md:pl-3 mt-4 md:mt-0">
			<%= render partial: "resources/reminders", locals: { resource: @account } %>
		</div>
	</div>
</div>

app/views/accounts/_advanced_search_results.html.erb
<div class="overflow-x-auto sm:rounded-lg mt-10">
  <table class="text-sm text-left text-gray-500">
    <thead class="text-xs text-gray-800 dark:text-white uppercase bg-gray-50 dark:bg-gray-700 whitespace-nowrap">
      <th scope="col" class="px-6 py-3">Name</th>
      <th scope="col" class="px-6 py-3">Assigned To</th>
      <th scope="col" class="px-6 py-3">Billing Address</th>
      <th scope="col" class="px-6 py-3">Shipping Address</th>
      <th scope="col" class="px-6 py-3">Phone Number</th>
      <th scope="col" class="px-6 py-3">Annual Revenue</th>
      <th scope="col" class="px-6 py-3">Number of Employees</th>
      <th scope="col" class="px-6 py-3">Industry</th>
      <th scope="col" class="px-6 py-3">Website</th>
      <th scope="col" class="px-6 py-3">Incorporation Date</th>
      <th scope="col" class="px-6 py-3">Source</th>
      <th scope="col" class="px-6 py-3">Last Activity At</th>
      <th scope="col" class="px-6 py-3">Created By</th>
      <th scope="col" class="px-6 py-3">Last Updated By</th>
    </thead>
    <tbody>
      <% @builder.results.each do |account| %>
        <tr class="bg-white hover:bg-gray-50 dark:bg-gray-500 dark:hover:bg-gray-400 text-gray-800 dark:text-white border-b border-gray-300 dark:border-gray-600">
          <th scope="row" class="px-6 py-4 font-medium whitespace-nowrap">
            <%= link_to account.name, account, data: { turbo: false } %>
          </th>
          <td class="px-6 py-4">
            <%= link_to_user(account.owner, data: { turbo: false }) %>
          </td>
          <td class="px-6 py-4">
            <%= address_display(account.billing_address) %>
          </td>
          <td class="px-6 py-4">
            <%= address_display(account.shipping_address) %>
          </td>
          <td class="px-6 py-4">
            <%= phone_display(account.phone_number) %>
          </td>
          <td class="px-6 py-4">
            <%= number_to_currency(account.annual_revenue) %>
          </td>
          <td class="px-6 py-4">
            <%= number_with_delimiter(account.number_of_employees) %>
          </td>
          <td class="px-6 py-4">
            <%= account.industry&.name %>
          </td>
          <td class="px-6 py-4">
            <%= website_display(account.website) %>
          </td>
          <td class="px-6 py-4">
            <%= incorporation_date_display(account.incorporation_date) %>
          </td>
          <td class="px-6 py-4">
            <%= account.account_source&.name %>
          </td>
          <td class="px-6 py-4">
            <%= account.last_activity_at %>
          </td>
          <td class="px-6 py-4">
            <%= link_to_user(account.created_by, data: { turbo: false }) %>
          </td>
          <td class="px-6 py-4">
            <%= link_to_user(account.last_updated_by, data: { turbo: false }) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/accounts/_deals.html.erb
<div class='bg-white dark:bg-gray-800 text-gray-800 dark:text-white border border-gray-300 dark:border-gray-900 shadow rounded-md p-4'>
  <h5 class="font-bebas-neue text-4xl">Deals</h5>
  <table class="text-sm text-left text-gray-500 mt-4">
    <thead class="text-xs text-gray-800 dark:text-white uppercase bg-gray-50 dark:bg-gray-700 whitespace-nowrap">
      <th scope="col" class="px-6 py-3">Name</th>
      <th scope="col" class="px-6 py-3">Stage</th>
      <th scope="col" class="px-6 py-3">Close Date</th>
      <th scope="col" class="px-6 py-3">Amount</th>
    </thead>
    <tbody>
      <% deals_for_account.each do |deal| %>
        <tr class="bg-white hover:bg-gray-50 dark:bg-gray-500 dark:hover:bg-gray-400 text-gray-800 dark:text-white border-b border-gray-300 dark:border-gray-600">
          <td class="px-6 py-4"><%= link_to deal.name, deal, data: { turbo: false } %></td>
          <td class="px-6 py-4"><%= deal.stage&.name %></td>
          <td class="px-6 py-4"><%= deal_close_date_display(deal) %></td>
          <td class="px-6 py-4"><%= deal_amount_display(deal) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/accounts/_details.html.erb
<div class='bg-white dark:bg-gray-800 text-gray-800 dark:text-white border border-gray-300 dark:border-gray-900 shadow rounded-md p-4'>
  <h2 class="font-bebas-neue text-4xl">Details</h2>
  <div class="py-4 border-b border-gray-300">
    <div>
      <span class="font-bold">Description: </span>
      <span><%= @account.description %></span>
    </div>
    <div class="md:grid md:grid-cols-2 md:gap-4 mt-4">
      <% if @account.parent_id.present? %>
        <div>
          <span class="font-bold">Parent: </span>
          <span><%= link_to @account.parent.name, account_path(@account.parent) %></span>
        </div>
      <% end %>
      <div>
        <span class="font-bold">Annual Revenue: </span>
        <span><%= number_to_currency(@account.annual_revenue) %></span>
      </div>
      <div>
        <span class="font-bold">Number of Employees: </span>
        <span><%= number_with_delimiter(@account.number_of_employees) %></span>
      </div>
      <div>
        <span class="font-bold">Shipping Address: </span>
        <span><%= address_display(@account.shipping_address) %></span>
      </div>
      <div>
        <span class="font-bold">Billing Address: </span>
        <span><%= address_display(@account.billing_address) %></span>
      </div>
      <div>
        <span class="font-bold">Phone Number: </span>
        <span><%= phone_display(@account.phone_number) %></span>
      </div> 
      <div>
        <span class="font-bold">Industry: </span>
        <span><%= @account.industry&.name %></span>
      </div>
      <div>
        <span class="font-bold">Website: </span>
        <span><%= website_display(@account.website) %></span>
      </div>
      <div>
        <span class="font-bold">Incorporation Date: </span>
        <span><%= incorporation_date_display(@account.incorporation_date) %></span>
      </div>
      <div>
        <span class="font-bold">Account Source: </span>
        <span><%= @account.account_source&.name %></span>
      </div>
      <div>
        <span class="font-bold">Last Activity At: </span>
        <span><%= @account.last_activity_at %></span>
      </div>
    </div>
  </div>
    <div class="pt-4">
    <h6 class="text-xl">System Information</h6>
    <div class="md:grid md:grid-cols-2 md:gap-4 mt-4">
      <div>
        <span class="font-bold">Created By: </span>
        <span><%= link_to_user(@account.created_by) %></span>
      </div>
      <div>
        <span class="font-bold">Created At: </span>
        <span><%= @account.created_at %></span>
      </div>    
      <div>
        <span class="font-bold">Last Updated By: </span>
        <span><%= link_to_user(@account.last_updated_by) %></span>
      </div>
      <div>
        <span class="font-bold">Last Updated At: </span>
        <span><%= @account.updated_at %></span>
      </div>
    </div>
  </div>
</div>

app/views/accounts/_form.html.erb
<%= form_with(model: account, class: "contents") do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul class="list-disc ml-6">
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="relative z-0 w-full mb-5 md:mb-10 group">
    <%= form.text_field :name, required: true, class: "block py-2.5 px-0 w-full text-lg text-gray-800 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" %>
      <%= form.label :name,  class: "peer-focus:font-medium absolute text-lg text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>    
  </div>

  <div class="relative z-0 w-full mb-5 md:mb-10 group">
    <%= form.select :owner_id, options_for_all_users(selected: selected_resource_owner(@account)), { required: true }, class: "block py-2.5 px-0 w-full text-lg text-gray-800 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" %>
    <%= form.label :owner_id, "Assigned To", class: "peer-focus:font-medium absolute text-lg text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>    
  </div>

  <div class="relative z-0 w-full mb-5 md:mb-10 group">  
    <%= form.text_area :description, class: "block py-2.5 px-0 w-full text-lg text-gray-800 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" %>
    <%= form.label :description, class: "peer-focus:font-medium absolute text-lg text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %> 
  </div>

  <div class="relative z-0 w-full mb-5 md:mb-10 group">  
    <%= form.text_field :annual_revenue, class: "block py-2.5 px-0 w-full text-lg text-gray-800 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" %>
    <%= form.label :annual_revenue, class: "peer-focus:font-medium absolute text-lg text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %> 
  </div> 

  <div class="relative z-0 w-full mb-5 md:mb-10 group">  
    <%= form.text_field :number_of_employees, class: "block py-2.5 px-0 w-full text-lg text-gray-800 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" %>
    <%= form.label :number_of_employees, class: "peer-focus:font-medium absolute text-lg text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %> 
  </div>

  <div class="relative z-0 w-full mb-5 md:mb-10 group">
    <%= form.select :industry_id, options_from_collection_for_select(Industry.all, :id, :name, @account.industry), { include_blank: true }, class: "block py-2.5 px-0 w-full text-lg text-gray-800 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" %>
    <%= form.label :industry_id, class: "peer-focus:font-medium absolute text-lg text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>    
  </div>

  <div class="relative z-0 w-full mb-5 md:mb-10 group">  
    <%= form.text_field :website, class: "block py-2.5 px-0 w-full text-lg text-gray-800 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" %>
    <%= form.label :website, class: "peer-focus:font-medium absolute text-lg text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %> 
  </div>

  <div class="relative z-0 w-full mb-5 md:mb-10 group">  
    <%= form.date_field :incorporation_date, class: "block py-2.5 px-0 w-full text-lg text-gray-800 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" %>
    <%= form.label :incorporation_date, class: "peer-focus:font-medium absolute text-lg text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %> 
  </div>

  <div class="relative z-0 w-full mb-5 md:mb-10 group">  
    <%= form.select :account_source_id, options_from_collection_for_select(AccountLeadSource.all, :id, :name, @account.account_source&.id), { include_blank: true }, class: "block py-2.5 px-0 w-full text-lg text-gray-800 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" %>
    <%= form.label :account_source_id, class: "peer-focus:font-medium absolute text-lg text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %> 
  </div>   



  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<% content_for :title, @account.name %>

<div class="w-11/12 md:w-5/6 mx-auto w-full py-8 px-3 md:px-0">
  <div>
    <%= link_to "Show this account", @account, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
    <%= link_to "See all accounts", accounts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  </div>

  <div class="mt-12 bg-white dark:bg-gray-800 text-gray-800 dark:text-white border border-gray-300 dark:border-gray-900 shadow rounded-md p-6">      
    <h1 class="font-bold text-4xl">Edit account</h1>
    <div class="mt-12">
      <%= render "form", account: @account %>
    </div>
  </div>  
</div>

app/views/accounts/index.html.erb
<% content_for :title, "Accounts" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Accounts</h1>
    <%= link_to "New account", new_account_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="accounts" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @accounts.any? %>
      <% @accounts.each do |account| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render account %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", account, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_account_path(account), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <div class="sm:inline-block">
              <%= button_to "Destroy", account, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No accounts found.</p>
    <% end %>
  </div>
</div>

app/views/accounts/new.html.erb
<% content_for :title, "New account" %>

<div class="w-11/12 md:w-5/6 mx-auto w-full py-8 px-3 md:px-0">
  <div>
    <%= link_to "See all accounts", accounts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  </div>
  <div class="mt-12 bg-white dark:bg-gray-800 text-gray-800 dark:text-white border border-gray-300 dark:border-gray-900 shadow rounded-md p-6">      
    <h1 class="font-bold text-4xl">Create new account</h1>
    <div class="mt-12">
      <%= render "form", account: @account %>
    </div>
  </div>
  
</div>

app/views/accounts/show.html.erb
<% content_for :title, @account.name %>

<div class="w-11/12 md:w-5/6 mx-auto w-full py-8 px-3 md:px-0">
  <div>
    <%= link_to "Edit this account ✏️", edit_account_path(@account), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
    <%= link_to "See all accounts 👀", accounts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>

    <% if current_user_is_admin? %>
      <div class="sm:inline-block mt-2 sm:mt-0 sm:ml-2">
        <%= button_to "Destroy this account 💣", @account, method: :delete, class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
      </div>
    <% end %>
    
    <%= link_to "Create New Reminder 🔔", new_reminder_path_for_resource(@account), class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-sky-500 hover:bg-sky-700 text-white inline-block font-medium" %>
  </div>

  <div class="py-8">
    <%= render @account %>  
  </div>
</div>